o-apiVersion: v1
kind: Service
metadata:
  name: app-test
  namespace: demo-prod-1
spec:
  selector:
    app: my-spring-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
